### ISSUE TITLE
Honor meritocracy

### ISSUE THREAD

**Issue by mikaelstaldal** [todogroup/opencodeofconduct#33]
Open source communities often function as meritocracies, and that is good since meritocracy is a way to avoid discrimination based on gender, ethnicity and other *irrelevant* characteristics.

However, meritocracy is in a way discrimination based on *technical* *ability*. So it is not a good idea to treat *technical* *ability* equally with gender, ethnicity and the other characteristics. Technical ability is, in the context of an open source community, a *relevant* characteristic.

I suggest that you remove *technical* *ability* from the Diversity Statement. Or at least treat it differently than the other characteristics in the list. It might be appropriate to explicitly honor diversity in technical ability as well as the other characteristics. But it is not appropriate to not tolerate discrimination based on technical ability.

**Comment by ciafwywcoc** [comment]
I agree. That's why I wrote my won COC that's a lot simpler and more conductive to encouraging the development of technical ability. See it here: ;) 
https://github.com/ciafwywcoc/ciafwywcoc/blob/master/CODE_OF_CONDUCT

**Comment by bkeepers** [comment]
Hi @mikaelstaldal. I think you raise an interesting point. While I agree that technical may be a little different from some of the more permanent characteristics, I think it's important that people that are just learning the ropes can do so without fear of being ridiculed for their lack of experience. Open source is a scary place, especially for someone that is new.

I'll leave this open for a few days to give others a chance to chime in, but I think it's important that we welcome learners.

**Comment by mikaelstaldal** [comment]
It's good to welcome learners, but we should not pretend that we will treat them equally to the more experienced developers from day one.

**Comment by ciafwywcoc** [comment]
I doesn't matter how experienced someone is. What matters is how good their contribution is. If it's not a contribution they should get lost. If the contribution sucks, they contributor deserves criticism and perhaps even ridicule, because asking someone kindly to improve just doesn't work. 

I, myself, when contributing to other projects, was told off before for being lazy and not filling in my commit messages well, and for not following the code layout standards. My butt was kicked for not writing tests. And I'm glad it was. My contributions became all the better for it. 

My advice to all people who want to get into programming is to learn how to deal with criticism, even harsh or rude criticism in a positive way. As a programmer you'll make dozens of mistakes every day, and you won't be able to catch all of those. First, be your own greatest critic. Secondly accept your own imperfections when they are pointed out by others. If we look at great programers like Carol Shaw or Dennis Richie, then we see modest people who were able to take criticism well.

**Comment by epsalon** [comment]
Meritocracy doesn't actually exist. Please read more on http://geekfeminism.wikia.com/wiki/Meritocracy
If you mention meritocracy positively in your CoC you will alienate a large part of your community. I know I won't take part in it.

**Comment by Addvilz** [comment]
I do agree with @bkeepers on this one - we should encourage welcoming environment, including for contributors lacking particular experiences and skills. Nobody should be reduced or ridiculed for lack of particular skill, instead, we should cultivate environment of learning. There exists mechanisms to control and review contributions - pull requests, code reviews and similar, so if the contribution is of bad quality, address the contribution, not the author of the contribution, as the latest is not only unjust to the contributor, but can and does lead to passing on good ideas just because someone lacks particular skill to implement them.

@epsalon, I would like to point out that this is not a Feminist movement side project (or at least I hope so). If you base your argument on an authoritative source, use a source authority of which is recognized by individuals outside the Feminist community. I would also like to point out, that this is "our community", as you seem to also be part of it. If you do not want to be part of it, nobody will force you, as you are entitled to execute free will and act accordingly.

**Comment by epsalon** [comment]
If you visit the link I posted, you would see that the damage to diversity by so-called "meritocracy" systems have been shown in academic research.
I thought the point of this code of conduct is to facilitate inclusion for a diverse group of people, including marginalized people. If that is the point, then supporting a so-called meritocracy would be counterproductive.

**Comment by Addvilz** [comment]
@epsalon I did visit the link and I also have quickly look'd through both articles linked to it (would help others not to link to paid resources tho...) and I have yet to see a single sentence that says anything even close to that meritocracy damages diversity. The publications does state the, in my opinion, abuse of a radicalized meritocracy can lead to inequality, but how does that affects diversity?

The point of this code of conduct is to facilitate fair treatment to everyone **without exclusion**. I think it covers it all pretty clearly.

My opinion is, meritocracy is a good thing to the point it gets abused, as many other things. I recognize the problem that meritocracy seems to be abused quite a lot, and till that changes, I am as well against supporting it, at least not in it's current form and definition.

**Comment by mikaelstaldal** [comment]
@epsalon Perhaps the title of this issue is misleading. I do not advocate mentioning meritocracy at all in the CoC. I just want the CoC to be compatible with meritocracy, and I think we can make it so by removing the mentioning of *technical* *ability*. This will not make meritocracy mandatory, but optional.

BTW, If you mention *feminism* positively in your CoC you will alienate a large part of your community.

**Comment by mikaelstaldal** [comment]
@Addvilz If it's only about reviewing pull requests, meritocracy is not needed and can probably even be harmful.

But, we also need to decide who should review the pull requests, and decide about whether to accept it or not (there can be disagreements about that). Here meritocracy can be useful.

**Comment by mikaelstaldal** [comment]
The facilitation of inclusion for a diverse group of people cannot be the *only* goal of the CoC. The primary goal should be to efficient development of useful software of high quality.

**Comment by Addvilz** [comment]
Yes, but that should be covered by contribution guidelines, not code of conduct.

Also, I can't really agree on the last statement of yours - CoC set's ground rules for interaction. As to what to develop, how and why, it's a different question entirely.

**Comment by mikaelstaldal** [comment]
@Addvilz I don't think it's wise to have the CoC contradict what you might want to put into contribution guidelines or otherwise practice within the project.

**Comment by Addvilz** [comment]
Yes, but I don't believe it does contradict - it think the meaning of the diversity statement more or less says something along the line "don't ridicule people with less technical skill than you do".

**Comment by mikaelstaldal** [comment]
So *no* *discrimination* merely mean "don't ridicule"?

**Comment by Addvilz** [comment]
Of course not. Why would it?

**Comment by ciafwywcoc** [comment]
What's wrong with ridicule, as long as it is targeted to the contribution itself? Again, asking people nicely often just doesn't work. Most people need a kick their ass to get in gear. I know for one I do, at times!

I also read the abstracts of the academic articles, too bad the full texts are behind a paywall.
What they seem to boil down to is that in commercial organizations, even if people have equal merit, managers will still prefer to give rewards to men over women. Probably because men tend to be more outspoken about their achievements, while women tend to be more modest. Of course that sucks. But it doesn't mean meritocracy is wrong. Rather, this is a *failure* to be truly meritocratic. 
The problems that more attention is paid to the people who scream the loudest. By focusing on actual contributions and their quality, we can get rid of these loud, yet useless voices.

Whether the insistence of technical ability scares people away though is a different matter. It's true that if you want to contribute to a FLOSS project, you need to have the courage to put up your contribution to severe scrutiny. I could see why some people might be afraid to do this. But if you don't have the confidence that your contribution is any good, then how will you convince others it is?   

And a contribution doesn't have to be source code. It can also be a bug report or a feature request. If someone has an idea to improve a project, but lack the technical skill to code it, they can simply describe in detail what they want as a feature request. And those are very valuable as well.

**Comment by alice-chu** [comment]
Let me offer a fresh perspective, as a minority woman working in the software industry. Around my workplace I hear incessant complaining about diversity issues, meritocracy, and microaggressions. But where is all of this chatter coming from? In reality it is a tiny sliver of the population:

 * People who have no talent or work ethic so they have to play the gender card to get others to listen to them.
 * Certain groups (to remain unnamed) who have a vastly exaggerated view of their innate abilities, and go through life with a chip on their shoulder, always blaming others for their shortcomings.
 * Other people who are very good at drawing attention and creating drama, but aren't really interested in nerdy computer stuff. Of course they still want a paycheck.
 * Guys who think that writing blog posts about their feminist cred will get them a date. Hint to Poindexter, it won't, try hitting the gym and go buy some decent clothes.

The real question is: are your communities better off with or without this drama? When was the last time adopting a CoC brought in a top contributor, please go ahead and name names.

**Comment by ciafwywcoc** [comment]
@alice-chu  :+1: Indeed, we're better off without all this drama and excluding these loudmouthed bullies who don't contribute anything of value. 

The problem is that those losers won't leave us be. Everyone must bow to their ideology or be mercilessly persecuted. It's not just FLOSS, they're active in all aspects of culture, literature, gaming, metal music, etc, etc. You are "lucky" in a sense because you are part of a minority group and they cannot attack you without exposing their hypocrisy.  For the average so called "white cis scum" programmer though, if we dare to oppose them,  they will try to get us kicked out from our projects, get our projects removed from Github and even go after our jobs. I clearly want to say NO to that, but to protect my family and my livelihood, I feel forced to do so using an alt using anonymizing technology...

**Comment by bkeepers** [comment]
Thanks for the lively discussion, everyone. This is a very meta conversation, and there are many other places on the internet that have discussed these topics at great length and depth. If you want to discuss specific word changes, feel free to open a pull request.

> It's good to welcome learners, but we should not pretend that we will treat them equally to the more experienced developers from day one.

@mikaelstaldal The purpose of the diversity statement is to communicate that diversity is valued and, more importantly, no one will be excluded from participating. It does not guarantee democracy.

I know the projects I help maintain have participants with less experience than others. Their participation is valued, but it doesn't mean they overrule more experienced users.
