### ISSUE TITLE
"Including participants with disabilities"?

### ISSUE THREAD

**Issue by mvirkkunen** [todogroup/opencodeofconduct#64]
[Note: I explicitly do not consent to the code of conduct as it is due to multiple issues]

What does this part mean exactly?

> We will not tolerate discrimination based on any of the protected characteristics above, including participants with disabilities.

As it reads currently, I would interpret it as meaning that participants with disabilities that might affect their output are not exempt from following the rules. So for instance, if somebody with Tourette syndrome cannot help calling other people names, they're shit out of luck? I think that's unreasonable, because they're not doing it on purpose.

**Comment by gyehuda** [comment]
I'm not sure if you are suggesting that people who suffer from Tourette Syndrome should be discriminated against or should be free to mistreat others? Both seem unreasonable for a CoC to suggest. So let's play out the scenarios: Imagine a project where one member, Alice, has some sort of disability that causes her to call other people pejorative names. (Note: given the common symptoms of Tourette, it would be unlikely that the associated tics would result in name calling in an online-forum, perhaps at an in person meeting. Moreover it would not be name-calling, but possibly small outbursts that might make others feel uncomfortable. But for the sake of this comment, let's consider a disorder that is so severe that it causes someone to come across as a complete troll on the internet. Surely such a disorder exists.)

Case 1: Alice lashes out against Bob in the community. Bob registers a complaint to Charlie, who receives it at the abuse@ email. Based on the CoC, Bob has the right to complain and Charlie will take the complaint seriously. Bob should not be a victim of abuse in Charlie's community. So Charlie investigates and learns that Alice has a severe disorder that causes her to be a troll against Bob. This is a problem that Charlie has to resolve in some manner. The CoC does not specify how to rectify this problem. It simply asserts that Bob's complaint will be taken seriously since the code seeks to protect members of the community from abusive behaviors. The specifics of the situation should help guide a good resolution.

Case 2: Bob lashes out at Alice in the online forum since he hears that she has a mental disorder that she struggles to control. Alice registers a complaint to the abuse@ email. She has a right to complain since she is being mistreated based on her having a disability. Charlie investigates and learns that indeed Alice has a disability, and that Bob is using this fact to mistreat her. Based on the CoC, Bob's mistreatment of Alice should not be tolerated. 

Your interpretation -- that (in Case 1) Alice is except from the rules since she may claim her disability/disorder gives her permission to grief others with impunity -- is not the intent of the CoC, nor is it what the CoC actually says. The "we will not tolerate" clause is related to the act of the abuser against others. The intent of the clause is Case 2 -- that projects using this type of CoC will not tolerate discrimination against people with disabilities.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
