### ISSUE TITLE
Diversity in technical ability

### ISSUE THREAD

**Issue by mvirkkunen** [todogroup/opencodeofconduct#65]
[Note: I explicitly do not consent to the code of conduct as it is due to multiple issues]

> we explicitly honor diversity in [...] technical ability

To me that is essentially saying that you cannot "discriminate" against people who write crap code by not merging their pull requests. This is unacceptable for any tech project imaginable.

If this is supposed to mean something else, it should be clarified.

**Comment by gyehuda** [comment]
Your point is well made. The authors did not intend that all project must accept all pull requests from all people with no considerations of their technical abilities of the merit of the code. I guess we assumed that most people would understand that treating people with respect does not mean accepting everything they contribute. Sorry if that point was not clear or if our assumption was too narrow. If you can suggest a better wording, that will help clarify this point for others reading this who might have concluded what you did.

The intent: it would be unacceptable to _mistreat_ someone based on their technical abilities. When a project does not accept a pull request (for what ever reason) most would not consider that a mistreatment of someone's dignity, but a technical judgement call. Projects make judgement calls all the time. Project leaders explain their judgement rationally (e.g. "We decided not to port this kernel code to VB.") but they don't have to engage in mistreatment (e.g. adding a pejorative put-down statement attacking the person who made the suggestion). Healthy communities welcome the perspectives of many, including those who are new to tech (or new to the project's technical focus area). Those with differing (or downright poor) tech-abilities might still be able contribute to the projects successfully (perhaps by working on less-technical aspects of the projects and learning along the way). And those who have nothing to contribute can be treated warmly still since they obviously want to help the project, and maybe will by getting others to help out instead.

**Comment by cperciva** [comment]
I think the problem here is that the word "discriminate" is overbroad for the contexts where it is being used.  In a literal sense it means "distinguish between", and in the common construction "discriminate against" it means "distinguish and treat differently" -- but that covers far more than "distinguish and mistreat".

I would suggest changing

    We will not tolerate discrimination based on any of the protected characteristics above

to 

    We will not tolerate harassment based on any of the protected characteristics above

**Comment by mvirkkunen** [comment]
Then perhaps this item should be removed from the list of special "explicitly forbidden" characteristics, because what you actually intended should be covered by a standard "no personal attacks" clause which is already understood to be part of the code of conduct of most projects even if they don't write it down.

**Comment by bkeepers** [comment]
This was previously discussed in https://github.com/todogroup/opencodeofconduct/issues/33

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
