### ISSUE TITLE
mrw

### ISSUE THREAD

**Issue by flashwave** [todogroup/opencodeofconduct#71]
![1423320222486](https://cloud.githubusercontent.com/assets/5001057/9074610/8870ef6c-3b0b-11e5-8efa-3c46d2b7f6bf.png)

**Comment by atarzwell** [comment]
I sympathise with this, but understand, while I got a chuckle out of it, this is far from constructive.

They seem willing to work with the community which is a necessity for developing a community Code of Conduct. Open an issue to discuss. If you don't want to get involved in the bikeshedding party. Then read others contributions and bust out the thumbs :+1:  or :-1: so we have a articulate communal voice as a community. 

If they are unwilling to work, that will become apparent, and hopefully github will find a less biased team to develop a community Code of Conduct. 

If you crapflood threads, it gives them power to close them without addressing legitimate issues in them. 

I mean this with no disrespect. 

I would love to have gotten an answer to @just3ws 's final comment on #17 but the derailed conversation got it closed :unamused:

**Comment by KelseyDH** [comment]
+1 @atarzwell

**Comment by just3ws** [comment]
Threads are being closed even before they get derailed and unfortunately there isn't an alternative forum. I've tried to raise a core member on Twitter but no response.

**Comment by KuraFire** [comment]
@just3ws i'm not part of the team but I can answer some of your questions from #17:

> Who is the arbiter of privilege?

The countless scientific studies into privilege, -isms, their detrimental effects, structural oppression, intersectional humanities, etc.

> Who makes the decision about when racism or sexism or whatever is okay and when it isn't?   

Generally it's never okay, but the severity of punishment for a certain action should correlate to the severity of the damage the action caused. Leadership can always treat things on a case by case basis. Targets of specific racism/sexism/etc. should be given the opportunity to have their voices heard in a situation or dispute. 

If any of that worries you, welcome to life as a slightly, *slightly* less privileged person for the first time ever.

> That puts a lot of pressure on community leaders that isn't fair. 

If you don't want the responsibility of having to educate yourself about how all of these things work and how they affect people and how your leadership is crucial in protecting people’s rights and freedoms and how screwing it up can really damage [everything], then perhaps you’re not a suitable person to lead (yet). I don't hear capable community leaders having a problem with CoC's at all, like, ever.

> This should be about protecting everyone's ability to participate in the community. It should not be about taking people who have arbitrarily been deemed as privileged down a peg or two.

Thankfully, none of this stuff has ever been arbitrarily determined.

**Comment by atarzwell** [comment]
This seems like most the information I found when trying to figure out what was happening here. 

> The countless scientific studies into privilege, -isms, their detrimental effects, structural oppression, intersectional humanities, etc.

While I don't want to get into a debate here, I am interested what you found that was scientific. I've only found humanities papers, which depending on how you search (and clear your filter bubble) you can find a seemingly official paper to confirm any bias you can think of. 

Hard science seems to collide with this, as demonstrated in the opal transphobia issue, where information about chromosomes were considered hate speech.  (I'm phrasing this as neutrally as I can in order to respond, I understand the context of the tweet may mean different things to different people, I do not intend to assert my own opinion, nor offend anyone.) 

If we have different definitions of "science" then disregard, if you have information based in hard science please tweet it at me (or email my github username @ gmail). 

That aside what was meant by asking: 
>Who is the arbiter of privilege?

I took as a more practical question. I just read a post on another forum where one person was accusing another of disrespecting them by calling them a "Northerner"[1]. They were somewhere in the UK, but I didn't (and still don't) have any context on that. By this "Oppressor/Oppressed" theory, there may be an answer, but not being in that region, nor having any means to find unbiased information about it, how do you make a call on that? Is there a list or an authority on this? 

[1] Again, not trying to offend, just quoting. Seriously if you understand this tweet/email me. Google isn't much use on this one. :)

Even if there could be an undisputed, unbiased, and complete list...

What about more complex ones? (For this thought experiment whites and males are the oppressors) A white female is constantly making slights at a black male, the black male gets frustrated with this and calls her a misogynistic slur. Who/how do you decide which is worse? 

This is also the internet, what about people who choose androgynous usernames and gender/raceless profile photos. We can't separate them into oppressor and oppressed, do we demand their race/gender in order to select their punishment? If that is somehow appropriate, do we retroactively ban them if they're found to be lying?

I think choosing your guilty status based on "are you in our list of good/bad categories" adds a level of complexity and more so uncomfortably feels like reverting back to abhorrent ideas like apartheid.

> Generally it's never okay

You can stop there. We know. We agree. We also know people make mistakes. We also know when to apologize, because lastly we also know you get removed if you are going to be a jerk. 

> If you don't want the responsibility of having to educate yourself about how all of these things work and how they affect people and how your leadership is crucial in protecting people’s rights and freedoms and how screwing it up can really damage [everything], then perhaps you’re not a suitable person to lead (yet). I don't hear capable community leaders having a problem with CoC's at all, like, ever.

I came here to commit, not to convict. 
![Book em](https://i.imgur.com/PE53Tzw.png)
I came here to write software, not to feel the thrill of being both Social Juris Doctor and Executioner.

For this CoC I don't have much of a problem, it has reasonable parts and there's hope, and there's a PR that's trying to clean up some of the controversial, condescending, disrespectful and ambiguous language, and some rules that somehow got included but don't have a demonstrable use. It is unnecessary? Maybe. Do I want to work in an environment where targeting and harassing people is acceptable? Nope. Am I ok with putting that on paper? That's exactly what we're bikeshedding about here. 

Join the party! We're no kool-ade allowed and you can check your personal politics and agendas at the door. This is a Code of Conduct for developing software, not a philosophy thesis. 

  :smiley:

**Comment by just3ws** [comment]
@KuraFire Thanks for you reply.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
