### ISSUE TITLE
Is there agreement on the definition of racism?

### ISSUE THREAD

**Issue by metabench** [todogroup/opencodeofconduct#86]

**Comment by gyehuda** [comment]
We don't need to define racism in order to have a useful Code of Conduct. 

Projects should not tolerate harassment, abuse, racism, sexism, or any malevolent behaviors that harm project members and the project itself. What exactly does this entail? The Code of Conduct is not a dictionary, especially for terms that are subjective in nature. Humanity may never agree on the strict definition of racism. Random people on a GitHub thread won't either. Most apply the *Duck Test* "If it quacks like a duck, I'll assume it's a duck." or *Justice Stewart Rule* "I know it when I see it." (This was said in reference to the failed attempt to agree on a strict definition of obscenity.) These are not fool-proof rules. The world is imperfect. 

If someone feels harmed, they should raise the issue to a responsible party via the abuse-email (and not play out the fight on the community forum). Racism is one of the potential harms that are found online. If you feel it is being used in the community, say something and hope that the project managers can help resolve the situation. We can proceed even without a unanimous definition of racism. Instead, the project managers will evaluate each complaint for its merit and resolution options.

**Comment by metabench** [comment]
@gyehuda Is it worth keeping this open to encourage more discussion on the subject?

Having looked through the previous discussions, the lack of a commonly understood definition of 'racism' in particular was one of the aspects that hindered effective communication on the issue.

My observation so far is that the meanings of the word as interpreted by different people have been so far apart that it's as though a different dialect is being spoken, with a word of such significance having very divergent interpretations.

-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

But fair enough in saying you don't need to have this definition. My opinion is that such a definition would be very useful indeed, but I see your point about how humanity may never agree on it.

I totally disagree about "Random people on a GitHub thread won't either" as this is a platform where open collaboration takes place, and many different people have their own knowledge and life experience to bring to the discussion.

A definition may also be helpful in allowing project managers to recognise racist behaviour, to help solidify standards of what is acceptable and what is not, in easily understood terms.
