### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ywarnier** [todogroup/opencodeofconduct#94]
Hi, I would like to provide translations to French and Spanish. What would be the best way to do this?
In particular:
- should I define new index.md files with an -fr_FR and -es_ES suffix?
- should the header code (including the version) be extended to include a "language" item?

**Comment by gyehuda** [comment]
Thanks for the offer. It is very kind of you. Currently this project is on hold, so translating the current version would not be a good investment of effort since it's not a stable version. Given the permissive CC license on the text, you are welcome to create a translation, and you are welcome to modify the text to meet your community's needs. But as long as this project is on hold, it's not going to be receptive to new files at this time. I don't have an answer to the potential follow up question (...when will this project resume activity...).
